<a href="https://colab.research.google.com/github/Deepalichaubey/Deepalichaubey/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##Ques:-1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
#Ans:-Let's Create a 3x3 NumPy array with random integers between 1 and 100, and then interchange its rows and columns:-

import numpy as np

# Create a 3x3 array with random integers between 1 and 100
random_array = np.random.randint(low=1, high=101, size=(3, 3))

print("Original array:")
print(random_array)

# Interchange rows and columns (transpose the array)
interchanged_array = random_array.T

print("\nInterchanged array (rows and columns swapped):")
print(interchanged_array)


Original array:
[[20  5 77]
 [ 3 26 91]
 [69 84  3]]

Interchanged array (rows and columns swapped):
[[20  3 69]
 [ 5 26 84]
 [77 91  3]]
